### ISSUE TITLE
tuuzed 您好. 打扰您了,我在 MirrorApp 使用中遇到了问题,能否请教您一下?

### ISSUE THREAD

**Issue by fenglilinglegeluan** [tuuzed/WMirror#3]
我已经在有公网ip的服务器上运行 LightTunnel 监听端口.
需要设置 MirrorApp 哪些设置才能将屏幕映射到 公网上呢?
目前 MirrorApp 只能在局域网下使用.
很抱歉占用了您的时间,自己尝试解决没有成功......

**Comment by tuuzed** [comment]
新版的MirrorApp内网穿透服务换成了frp

**Comment by fenglilinglegeluan** [comment]
下午进行了尝试。。。又遇到新的问题
目前开启了frp服务，添加了子域名的解析

```
[主机记录 | 记录类型 | 线路类型 | 记录值 | 权重 | MX | TTL | 最后操作时间
* | A | 默认 | 42.192.228.1 | - | - | 600 | 2021-04-28 19:40:58 | 
```
但是访问 MirrorAPP 映射的 子域名:端口的网站时，卡在loading界面
表哥能指点一下吗？没有解决问题的头绪。。。

**Comment by fenglilinglegeluan** [comment]
尝试解决问题没成功。。。做了以下尝试

1.  用手机连 wifi ,局域网里另一台电脑使用 frpc 连接服务器，内网穿透 手机上 MirrorApp 的那个端口.
2.  frp 使用 tcp 协议访问 映射后的网站是可以看到画面 , 但是改成 http 就不行了.
子域名那个只能使用 http ，问题还是没解决 = =

**Comment by tuuzed** [comment]
这个是我的frps配置

```ini
[common]
bind_addr = 0.0.0.0
bind_port = 80

dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_user = root
dashboard_pwd = 123456

vhost_http_port = 80
subdomain_host = domain.com
```
注意domain.com需要换成自己的域名

**Comment by fenglilinglegeluan** [comment]
使用了和您一样的配置,但是访问 子域名:端口 的网站时,卡在loading界面, MirrorApp 的网站是可以进入的,就是加载不出手机屏幕的画面.
无奈换回了 v0.7.28 版本,服务端使用了 LightTunnel . 可以正常使用了.
查看服务器端的日志, 手机和服务器建立的是 tcp 链接.
```
2021-05-06 16:48:02 - [ INFO ] onConnected: tcp://localhost:9999<-tcp://:::4480
2021-05-06 16:48:10 - [ INFO ] onDisconnect: tcp://localhost:9999<-tcp://:::4480
```
使用 frp 时,日志提示建立了 http 的链接,我猜测我的问题是不是出在这里了...

**Comment by tuuzed** [comment]
目前MirrorApp使用的是http类型的frp隧道，你要确保frps端开启了http类型隧道支持

**Comment by fenglilinglegeluan** [comment]
嗯嗯,已经开启了http类型隧道支持，http链接也建立了。
但是一直卡在这个界面。
![Screenshot_20210527_223759_org mozilla firefox](https://user-images.githubusercontent.com/44286100/119846755-ff791380-bf3c-11eb-9aea-491e3ad350e7.jpg)
我现在用的是 LightTunnel的0.7.28版本了，好用!(^O^)y

**Comment by blue319** [comment]
> 尝试解决问题没成功。。。做了以下尝试
> 
> 1. 问题连体wifi卡，大地人分队一次，一次次大口大口地磨一次，一次次大口大口地把一次次的"大号"和"一次"的"大号"
> 2. frp tcpic 特克特克特克 · 利特 · 哈弗 · 斯泰尔 · 斯泰尔 · 里加 · 里希特 · 西格 · 普西格 ， 多维利 · 布约特 · 奇普 · 格布特不对比特·哈次要的哈托普，问题问题==
 
问题解决了吗？我也是一只卡在loading...界面
